version: '3'
services:
  database:
    image: mongo:4.2
    container_name: mongo4
    network_mode: host
    command: mongod --dbpath /data/db --port 27041 --config /resource/mongod.yml
    volumes:
      - ./standalone/config/mongod.yml:/resource/mongod.yml
      - /Users/eugenechen/Documents/Projects/demo_mongo_cluster/standalone/data:/data/db
